networks:
  reverse-proxy:
    external: true

volumes:
  mathesar-pgdata:
    external: true
  mathesar-media:
    external: true
  mathesar-static:
    external: true
  mathesar-secrets:
    external: true

services:
  postgres:
    image: docker.io/pgautoupgrade/pgautoupgrade:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    volumes:
      - mathesar-pgdata:/var/lib/postgresql/data
    networks:
      - reverse-proxy
    restart: unless-stopped

  mathesar:
    image: docker.io/mathesar/mathesar:0.8.0
    container_name: mathesar
    environment:
      DJANGO_SETTINGS_MODULE: ${MATHESAR_DJANGO_SETTINGS_MODULE}
      ALLOWED_HOSTS: ${MATHESAR_ALLOWED_HOSTS}
      DEBUG: ${MATHESAR_DEBUG}
      SECRET_KEY: ${MATHESAR_SECRET_KEY}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "curl -fsS http://localhost:8000 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - mathesar-media:/code/media
      - mathesar-static:/code/static
      - mathesar-secrets:/code/.secrets
    labels:
      traefik.enable: true
      traefik.http.routers.mathesar.rule: Host(`mathesar.hl.srdego.com`)
      traefik.http.routers.mathesar.entrypoints: websecure
      traefik.http.routers.mathesar.tls.certresolver: cloudflare-letsencrypt-acme
      traefik.http.services.mathesar.loadbalancer.server.port: "8000"
    networks:
      - reverse-proxy
    restart: unless-stopped
