networks:
  reverse-proxy:
    external: true

services:
  dockhand:
    image: fnsys/dockhand:latest
    container_name: dockhand
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks/dockhand/data:/app/data
    labels:
      traefik.enable: true
      traefik.http.routers.dockhand.rule: Host(`dockhand.hl.srdego.com`)
      traefik.http.routers.dockhand.entrypoints: websecure
      traefik.http.routers.dockhand.tls.certresolver: cloudflare-letsencrypt-acme
      traefik.http.services.dockhand.loadbalancer.server.port: "3000"
    networks:
      - reverse-proxy
    restart: unless-stopped
